--DROP tablespace ROSE;
--DROP tablespace ROSE_TEMP;
--DROP role RL_ROSE_USER;
--DROP user ROSE_USER cascade;

CREATE TABLESPACE ROSE
  DATAFILE 'C:\COURSE_WORK\ROSE.dbf'
  SIZE 10 M
  ONLINE;
    
CREATE TEMPORARY TABLESPACE ROSE_TEMP
TEMPFILE 'C:\COURSE_WORK\ROSE_TEMP.dbf'
SIZE 5 M
AUTOEXTEND ON NEXT 3 M
MAXSIZE 30 M
EXTENT MANAGEMENT LOCAL;

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

ALTER SESSION SET CONTAINER=CDB$ROOT;

CREATE ROLE RL_ROSE_USER;

GRANT CREATE SESSION TO RL_ROSE_USER;
GRANT CREATE TABLE,
      CREATE VIEW,
      CREATE PROCEDURE TO RL_ROSE_USER;
GRANT DROP ANY TABLE,
      DROP ANY VIEW,
      DROP ANY PROCEDURE TO RL_ROSE_USER;

CREATE USER ROSE_USER IDENTIFIED BY Root12345
DEFAULT TABLESPACE ROSE QUOTA UNLIMITED ON ROSE
TEMPORARY TABLESPACE ROSE_TEMP
ACCOUNT UNLOCK
PASSWORD EXPIRE

GRANT RL_ROSE_USER TO ROSE_USER;